import Head from "next/head";
import Image from "next/image";
import Makes from "@/components/Makes";
import LeaderBoard from "@/components/LeaderBoard";
import SearchTrees from "@/components/SearchTrees";
import CreateMake from "@/components/CreateMake";
import CreateModel from "@/components/CreateModel";
import UpdateRatio from "@/components/UpdateRatio";
import UploadVehicle from "@/components/UploadVehicle";
import LoginForm from "@/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Makes /> */}
      <div>-----------------------------------------</div>
      <LeaderBoard />
      <div>-----------------------------------------</div>
      <SearchTrees />
      <div>-----------------------------------------</div>
      <CreateMake />
      <div>-----------------------------------------</div>
      <CreateModel />
      <div>-----------------------------------------</div>
      <UpdateRatio />
      <div>-----------------------------------------</div>
      <UploadVehicle />
      <div>-----------------------------------------</div>
      <LoginForm />
    </>
  );
}
